/**
 * useSocialAuth Hook
 * Manages OAuth authentication flow with React Query
 */

import { useState, useCallback } from 'react';
import { useMutation } from '@tanstack/react-query';
import {
  SocialProvider,
  AuthMode,
  UserType,
  SocialAuthCallbackResponse,
  SocialAuthError,
  SocialAuthErrorCode,
  UseSocialAuthReturn,
} from '../types/social-auth';
import api from '../lib/api';
import { getSocialAuthErrorMessage } from '../config/social-auth-config';

// ============================================================================
// useSocialAuth Hook
// ============================================================================

/**
 * Hook for managing social authentication flow
 */
export function useSocialAuth(): UseSocialAuthReturn {
  const [error, setError] = useState<SocialAuthError | null>(null);

  /**
   * Initiate OAuth flow - Get auth URL and redirect
   */
  const initiateMutation = useMutation({
    mutationFn: async ({
      provider,
    }: {
      provider: SocialProvider;
      mode: AuthMode;
      userType?: UserType;
    }) => {
      // Get OAuth URL from backend
      const response = await api.getSocialAuthUrl(provider);

      return { authUrl: response.authUrl };
    },
    onSuccess: ({ authUrl }) => {
      // Redirect to OAuth provider
      window.location.href = authUrl;
    },
    onError: (err: any) => {
      const authError: SocialAuthError = {
        code: SocialAuthErrorCode.PROVIDER_ERROR,
        message: err?.message || getSocialAuthErrorMessage('provider_error'),
      };
      setError(authError);
    },
  });

  /**
   * Handle OAuth callback - Exchange code for tokens
   */
  const callbackMutation = useMutation({
    mutationFn: async ({
      provider,
      code,
      state,
    }: {
      provider: SocialProvider;
      code: string;
      state: string;
    }): Promise<SocialAuthCallbackResponse> => {
      // NOTE: State validation is handled by database backend
      // We don't validate state locally because it was generated by database

      // Exchange code for tokens via database
      const response = await api.handleSocialAuthCallback(
        provider,
        code,
        state
      );

      return response;
    },
    onError: (err: any) => {
      let errorCode = SocialAuthErrorCode.UNKNOWN_ERROR;

      if (err?.message?.includes('state')) {
        errorCode = SocialAuthErrorCode.INVALID_STATE;
      } else if (err?.message?.includes('code')) {
        errorCode = SocialAuthErrorCode.INVALID_CODE;
      } else if (err?.message?.includes('email') || err?.message?.includes('exists')) {
        errorCode = SocialAuthErrorCode.EMAIL_ALREADY_EXISTS;
      } else if (err?.message?.includes('network') || err?.message?.includes('connection')) {
        errorCode = SocialAuthErrorCode.NETWORK_ERROR;
      }

      const authError: SocialAuthError = {
        code: errorCode,
        message: err?.message || getSocialAuthErrorMessage(errorCode),
      };
      setError(authError);
    },
  });

  /**
   * Initiate OAuth flow
   */
  const initiateOAuth = useCallback(
    async (provider: SocialProvider, mode: AuthMode, userType?: UserType): Promise<void> => {
      setError(null);
      await initiateMutation.mutateAsync({ provider, mode, userType });
    },
    [initiateMutation]
  );

  /**
   * Handle OAuth callback
   */
  const handleCallback = useCallback(
    async (
      provider: SocialProvider,
      code: string,
      state: string
    ): Promise<SocialAuthCallbackResponse> => {
      setError(null);
      return callbackMutation.mutateAsync({ provider, code, state });
    },
    [callbackMutation]
  );

  /**
   * Clear error state
   */
  const clearError = useCallback(() => {
    setError(null);
  }, []);

  return {
    initiateOAuth,
    handleCallback,
    isLoading: initiateMutation.isPending || callbackMutation.isPending,
    error,
    clearError,
  };
}

export default useSocialAuth;
